# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pwd-band

on:
  push:
    branches:
      - 1.5
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_891ab5f3d5384f49b0aaeb288120a483 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_84f184ff2662427a857de8aa1bbc3c21 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_891ab5f3d5384f49b0aaeb288120a483 }}/ltbproject/self-service-password:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pwd-band'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4164ee2646a442b2b842303b783bf5b9 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_891ab5f3d5384f49b0aaeb288120a483 }}/ltbproject/self-service-password:${{ github.sha }}'